from fpdf import FPDF
import os

# Ensure directory exists
output_dir = "/home/ubuntu/care-compliance-landing/client/public/documents"
os.makedirs(output_dir, exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Care Compliance System', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()) + ' | Generated by Care Compliance System', 0, 0, 'C')

def create_template(filename, title, sections):
    pdf = PDF()
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, title, 0, 1, 'L')
    pdf.ln(5)
    
    # Content
    pdf.set_font('Arial', '', 11)
    
    for section, items in sections.items():
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, section, 1, 1, 'L', 1)
        
        pdf.set_font('Arial', '', 11)
        for item in items:
            pdf.cell(10, 10, '[  ]', 0, 0)
            pdf.multi_cell(0, 10, item, 0, 1)
        pdf.ln(3)

    pdf.output(os.path.join(output_dir, filename))
    print(f"Created {filename}")

# --- ORIGINAL 13 TEMPLATES ---

# 1. Medication Audit
create_template("Medication_Audit.pdf", "Medication Administration Audit", {
    "Storage": ["Medication room temperature recorded daily", "Fridge temperature recorded daily", "Controlled drugs cupboard secure"],
    "Administration": ["MAR charts signed correctly", "No gaps in MAR charts", "PRN protocols in place"],
    "Competency": ["Staff competency assessments up to date", "Errors reported and investigated"]
})

# 2. Care Plan Audit
create_template("Care_Plan_Audit.pdf", "Care Plan Quality Audit", {
    "Personal Details": ["Next of kin details up to date", "DNACPR status recorded", "Allergies clearly documented"],
    "Assessments": ["Risk assessments reviewed monthly", "Waterlow score up to date", "MUST score up to date"],
    "Person Centred": ["Life history recorded", "Preferences and wishes documented", "Resident involvement evident"]
})

# 3. Infection Control (Original - renamed to avoid conflict or merged)
# We will use the NEW detailed one instead, but keep this for completeness if needed. 
# Actually, let's make this the "Daily Spot Check" version.
create_template("Infection_Control_Spot_Check.pdf", "Daily Infection Control Spot Check", {
    "Environment": ["Sluice room clean", "No clinical waste in general bins", "PPE stations stocked"],
    "Staff": ["Uniforms clean", "No stone rings/watches", "Hair tied back"]
})

# 4. Health & Safety
create_template("Health_Safety_Audit.pdf", "Health & Safety Walkaround", {
    "General": ["Corridors clear of obstruction", "Floors dry and free from trip hazards", "Lighting adequate"],
    "Maintenance": ["Radiator covers in place", "Window restrictors functional", "Water temperatures within range"]
})

# 5. Kitchen Audit
create_template("Kitchen_Audit.pdf", "Kitchen & Food Safety Audit", {
    "Hygiene": ["Staff wearing hats/aprons", "Hand wash basin accessible", "Cleaning schedule signed"],
    "Food Storage": ["Fridge/Freezer temps recorded", "Open food labelled and dated", "Dry store organised"]
})

# 6. Staff File Audit
create_template("Staff_File_Audit.pdf", "Staff Personnel File Audit", {
    "Recruitment": ["Application form complete", "Interview notes on file", "2 References obtained"],
    "Checks": ["DBS certificate number recorded", "Right to work in UK verified", "ID documents copied"],
    "Training": ["Induction checklist complete", "Mandatory training certificates on file"]
})

# 7. Resident Room Check
create_template("Resident_Room_Check.pdf", "Resident Room Monthly Check", {
    "Cleanliness": ["Room visibly clean", "Bedding clean and changed", "En-suite clean"],
    "Safety": ["Call bell within reach", "Bed rails safe (if used)", "Furniture in good repair"],
    "Personal": ["Toiletries available", "Clothing labelled", "Personal items respected"]
})

# 8. Night Shift Check
create_template("Night_Shift_Check.pdf", "Night Shift Safety Check", {
    "Security": ["All external doors locked", "Windows secured", "Fire panel checked"],
    "Residents": ["Hourly checks completed", "Fluids offered", "Pad changes recorded"]
})

# 9. Spot Check (Newer batch)
create_template("Spot_Check_Form.pdf", "Manager's Daily Spot Check", {
    "Arrival": ["Reception area tidy", "Sign-in book used", "Odour control effective"],
    "Interaction": ["Staff interacting kindly", "Call bells answered promptly", "Residents appear comfortable"]
})

# 10. Supervision Record
create_template("Supervision_Record.pdf", "Staff Supervision Record", {
    "Discussion": ["Review of previous actions", "Wellbeing and support", "Training needs"],
    "Performance": ["Feedback on performance", "Areas for improvement", "Achievements"],
    "Actions": ["Agreed actions", "Date for next meeting"]
})

# 11. Medication Competency
create_template("Medication_Competency.pdf", "Medication Competency Assessment", {
    "Knowledge": ["Understands 6 rights of administration", "Knows side effects of common drugs", "Understands PRN protocols"],
    "Practice": ["Washes hands before rounds", "Checks MAR chart correctly", "Signs after administration"]
})

# 12. DBS Risk Assessment
create_template("DBS_Risk_Assessment.pdf", "Positive DBS Risk Assessment", {
    "Offence Details": ["Nature of offence", "Date of offence", "Relevance to role"],
    "Mitigation": ["Candidate's explanation", "References checked regarding character", "Supervision requirements"],
    "Decision": ["Outcome of assessment", "Manager signature", "Date"]
})

# 13. Business Continuity
create_template("Business_Continuity_Plan.pdf", "Business Continuity Plan Template", {
    "Emergency Contacts": ["Manager", "Owner", "Plumber", "Electrician", "Gas Supplier"],
    "Scenarios": ["Power failure", "Flood", "Fire", "Staff shortage", "IT failure"],
    "Evacuation": ["Assembly point", "Transport arrangements", "Temporary accommodation"]
})

# --- NEW 8 TEMPLATES ---

# 14. Staff Feedback
create_template("Staff_Feedback_Form.pdf", "Staff Feedback Questionnaire", {
    "Work Environment": ["I feel safe and supported", "I have access to resources", "Staffing levels are sufficient"],
    "Management": ["I can raise concerns", "I receive supervision", "Training is effective"],
    "Comments": ["Additional comments:\n\n\n"]
})

# 15. Service User Feedback
create_template("Service_User_Feedback.pdf", "Service User Feedback Form", {
    "Care": ["Staff treat me with respect", "I am involved in decisions", "Staff respond quickly"],
    "Home": ["My room is clean", "I feel safe", "Food is good"],
    "Comments": ["What do we do well?\n\n\n"]
})

# 16. Family Feedback
create_template("Family_Friends_Feedback.pdf", "Family & Friends Feedback Form", {
    "Communication": ["I am kept informed", "Staff are approachable", "I know how to complain"],
    "Care": ["My relative is treated well", "My relative is clean/comfortable", "Home is safe"],
    "Comments": ["Other feedback:\n\n\n"]
})

# 17. Professional Feedback
create_template("Professional_Feedback.pdf", "Visiting Professional Feedback Form", {
    "Cooperation": ["Staff are helpful", "Staff follow instructions", "Referrals are timely"],
    "Care": ["Residents appear well-cared for", "Care plans are accurate", "Medication is safe"],
    "Comments": ["Observations:\n\n\n"]
})

# 18. Fire Safety Checklist
create_template("Fire_Safety_Checklist.pdf", "Weekly Fire Safety Checklist", {
    "Alarm": ["Panel healthy", "Call point tested", "Sounders audible"],
    "Exits": ["Routes clear", "Doors unlocked", "Lighting green"],
    "Doors": ["Close fully", "Seals intact", "Hold-opens work"]
})

# 19. Infection Control Audit (Detailed)
create_template("Infection_Control_Audit.pdf", "Infection Prevention & Control Audit", {
    "Hand Hygiene": ["Bare below elbows", "Soap/towels available", "Technique posters up"],
    "PPE": ["Gloves/aprons available", "Stored correctly", "Used appropriately"],
    "Environment": ["Visibly clean", "No odours", "Bins not overflowing"]
})

# 20. Complaints Log
create_template("Complaints_Log.pdf", "Complaints & Concerns Log", {
    "Details": ["Date/Name", "Nature of complaint:\n\n"],
    "Investigation": ["Investigated by", "Findings:\n\n"],
    "Outcome": ["Action taken", "Complainant informed", "Upheld/Not Upheld"]
})

# 21. Training Matrix
create_template("Training_Matrix.pdf", "Staff Training Matrix Template", {
    "Mandatory": ["Fire Safety", "Moving & Handling", "Safeguarding", "Infection Control"],
    "Role Specific": ["Medication", "Dementia", "MCA/DoLS", "End of Life"],
    "Key": ["Red = Expired", "Amber = Expiring", "Green = In date"]
})
