import json
import os
from fpdf import FPDF
from pdf2image import convert_from_path

# Load template content
with open('template_content.json', 'r') as f:
    data = json.load(f)

# Ensure output directory exists
output_dir = "client/public/documents"
os.makedirs(output_dir, exist_ok=True)

class PDF(FPDF):
    def header(self):
        # Logo placeholder (text for now, could be image)
        self.set_font('Arial', 'B', 15)
        self.set_text_color(0, 51, 102) # Dark Blue
        self.cell(0, 10, 'Care Compliance System', 0, 1, 'L')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by Care Compliance System', 0, 0, 'C')

def create_pdf(template):
    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 20)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(0, 10, template['title'], 0, 1, 'L')
    
    # Category & Description
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Category: {template['category']}", 0, 1, 'L')
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 6, template['description'])
    pdf.ln(10)
    
    # Sections
    for section in template.get('sections', []):
        # Section Title
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, section['title'], 1, 1, 'L', 1)
        
        # Items
        pdf.set_font('Arial', '', 11)
        for item in section['items']:
            # Checkbox
            pdf.cell(10, 8, '[   ]', 0, 0)
            # Item text
            pdf.multi_cell(0, 8, item)
        pdf.ln(5)
        
    # Scoring/Notes if applicable
    if 'scoring' in template:
        pdf.ln(5)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 10, "Scoring / Methodology:", 0, 1, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(0, 6, template['scoring'])

    # Signature Block
    pdf.ln(15)
    pdf.set_font('Arial', '', 10)
    pdf.cell(90, 10, "Completed By: __________________________", 0, 0)
    pdf.cell(90, 10, "Date: __________________________", 0, 1)
    pdf.cell(90, 10, "Signature: __________________________", 0, 1)

    # Save
    filename = f"{output_dir}/{template['id']}.pdf"
    pdf.output(filename)
    print(f"Generated: {filename}")

    # Generate Thumbnail
    try:
        images = convert_from_path(filename, first_page=1, last_page=1)
        if images:
            thumb_filename = filename.replace('.pdf', '_thumb.jpg')
            images[0].save(thumb_filename, 'JPEG')
            print(f"Generated Thumbnail: {thumb_filename}")
    except Exception as e:
        print(f"Failed to generate thumbnail for {filename}: {e}")

# Generate all templates
for template in data['templates']:
    create_pdf(template)
